### ISSUE TITLE
papers/Bates.Nextjournal.2019.pdf is just the first page.

### ISSUE THREAD

**Issue by dmbates** [smlp2020-stream4/SMLP2020#16]
At least, when I try to view it using `evince` on Ubuntu I only get the first page.

**Comment by kliegl** [comment]
You are right. I tried to export from the nextjournal website. Looks like it did not work or I screwed it up. I can try again or do you have a pdf?  (One can get to the paper by clicking at the link in the stub.)  

To avoid pdfs entirely, I also thought about  having a list of paper links rather the pdfs at the repo. In the end I thought the current solution with the papers directory is simpler for participants.  If we were to put up links (possibly also to other stuff -- I had a long collection at moodle) where would one put such a page in the repo? (It would also be good to have (links) to tutorial intro pages integrated here.

**Comment by kliegl** [comment]
I think I found a very nice solution. nextjournal allows you to export the complete md file for the article. VS Code gives you a complete preview of md files (see cmd-shift p: markdown).  So I replaced the pdf with the md file.
