### ISSUE TITLE
Names of scripts and data

### ISSUE THREAD

**Issue by kliegl** [smlp2020-stream4/SMLP2020#5]
I propose to adopt a consistent style for naming participants' data and scripts, for exampe, a combination of last name and some characteristic of the study. Optional third elements of the name could specify, e.g., whether the script is MixedModel (MM) or lme4 based. Also if there are several comments on a submission -- could also come from participants, not only the instructors -- the initials of the reviewer could be included to disambiguate when the review is discussed in a session.

**Comment by dmbates** [comment]
Is it necessary to indicate that the `.Rmd` scripts use `lme4` and the `.jmd` scripts use `MM`?  Seems redundant.

**Comment by kliegl** [comment]
There is one example sleepstudy_borrowingingstrength_lme4.Rmd, *_lme4.jmd, *_MM.jmd where I implemented a pure R program in jmd. It was meant to ease the transition from Rmd to jmd. I don't think we will need for the other later example. So we could remove the redundancy for all but this one -- which I plan to use in the Monday morning session.

**Comment by dmbates** [comment]
To tell you the truth, I don't see the purpose in `sleepstudy_borrowingstrength_lme4.jmd`  If all the computing is being done in R why wrap it in a `.jmd` file?

**Comment by kliegl** [comment]
It is a simple intermediate step I want to use in my Monday morning lecture.
